# Array Indexing
1. Integer Indexing
2. Boolean Indexing

## Integer Indexing

In [1]:
# Initialize variables

import numpy as np 

list1 = [1,1.1,-5.45,3.2]
arr1 = np.array(list1)

list2 = [[1,1.1,-5.45,3.2],[-0.5,0.33,10.12,-5]]
arr2 = np.array(list2)

In [3]:
# 1d arrays are similar to python lists
print (arr1[0])
print (arr1[1:3])
print (arr1[-2:])

1.0
[ 1.1  -5.45]
[-5.45  3.2 ]


In [4]:
# 2d array indexing
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [5]:
arr2[0]

array([ 1.  ,  1.1 , -5.45,  3.2 ])

In [6]:
arr2[0][1]

np.float64(1.1)

In [12]:
arr1[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [7]:
arr2[0,1]

np.float64(1.1)

In [8]:
arr2[0,:3]

array([ 1.  ,  1.1 , -5.45])

In [9]:
arr2[:,:3]

array([[ 1.  ,  1.1 , -5.45],
       [-0.5 ,  0.33, 10.12]])

In [10]:
list2[:,:3]

TypeError: list indices must be integers or slices, not tuple

In [11]:
arr2[:,[1,3,-1]]

array([[ 1.1 ,  3.2 ,  3.2 ],
       [ 0.33, -5.  , -5.  ]])

In [13]:
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [14]:
arr2[:, [1, 2]]

array([[ 1.1 , -5.45],
       [ 0.33, 10.12]])

In [15]:
arr2[:, [-3, -2]]

array([[ 1.1 , -5.45],
       [ 0.33, 10.12]])

In [16]:
arr2[:, [1,2,-3,-2]]

array([[ 1.1 , -5.45,  1.1 , -5.45],
       [ 0.33, 10.12,  0.33, 10.12]])

In [22]:
arr2[:, [1, 1, 1,1,1,1,1]]

array([[1.1 , 1.1 , 1.1 , 1.1 , 1.1 , 1.1 , 1.1 ],
       [0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33]])

In [28]:
arr2[1, [1,1,1,1,1]]

array([0.33, 0.33, 0.33, 0.33, 0.33])

## Boolean Indexing

In [25]:
arr1

array([ 1.  ,  1.1 , -5.45,  3.2 ])

In [27]:
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [23]:
mask=arr1>0
mask

array([ True,  True, False,  True])

In [24]:
arr1[mask]

array([1. , 1.1, 3.2])

In [30]:
arr2[[False,True],:]

array([[-0.5 ,  0.33, 10.12, -5.  ]])

In [34]:
arr2[[True, True], :]

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [35]:
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [ ]:
mask = arr2 < 0
mask

In [ ]:
arr2[mask]

In [ ]:
arr2[mask]=0
arr2

In [37]:
arr2.mean()

np.float64(0.5999999999999999)

In [38]:
arr2.std()

np.float64(4.569543193799572)

In [40]:
arr2[0].mean()

np.float64(-0.03749999999999998)

In [41]:
arr2[1].mean()

np.float64(1.2374999999999998)